### PR TITLE
Show keyboard on search screen

### PR DESCRIPTION
**Pull request by Gnzlt**
I think it's a necessary UX improvement to show the keyboard when entering the Search screen, that way the user will be able to type straightaway without having to tap on the top bar.

### CODE REVIEW

**Comment by malikmotani** [comment]
@Gnzlt I think only `android:windowSoftInputMode="stateAlwaysVisible"` will work

**Comment by Gnzlt** [comment]
You need both, I already tried 😅

**Comment by malikmotani** [comment]
I tried with android:windowSoftInputMode="stateAlwaysVisible" and it's working :sweat_smile: 
I already created a new [PR](https://github.com/Mindinventory/VanillaPlacePicker/pull/15), can you please try this?

**Comment by Gnzlt** [comment]
Could you try typing after that? I'm not able to introduce characters in the EditText 😅

**Comment by Gnzlt** [comment]
This is what happens when I test both approaches in a Pixel 2. How does it works for you?

| Manifest tag | Manifest tag + Request Focus |
|---|---|
| manifestonly | requestFocus |

_Note: I get the same result on the left with your PR_

**Comment by malikmotani** [comment]
It worked with Moto G4, but I checked it with Pixel, it isn't working as expected.
Thanks for your contribution
motog4

**Comment by akashmi** [comment]
@Gnzlt 
Can you please update your PR?

**Pull request merged**
